{% set name = "balance" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa760bbe0e0f35920590c45c66b3c80190866d3e7fdfb0c47a2b3e885fd406e2

build:
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools-scm
    - python >=3.7
  run:
    - ipfn
    - ipython
    - matplotlib-base
    - numpy
    - patsy
    - pandas <=1.4.3
    - plotly
    - python >=3.7
    - seaborn <=0.11.1
    - scikit-learn
    - scipy <1.9.2
    - session-info
    - statsmodels

    # These dependencies are needed even though not listed in setup files
    - glmnet_py

test:
  source_files:
    - tests
  imports:
    - balance
  commands:
    - pip check
    - pytest -vvv -k "not test_weighted_comparisons_plots and not test_cbps_constraints" --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://import-balance.org/
  dev_url: https://github.com/facebookresearch/balance
  summary: Simple workflow and methods for dealing with biased data.
  license: GPL-2.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
