{% set name = "balance" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d993549b380c6910613d3f19c32d2b6d3247eedd3ea0e1ff2680627869c9cd9e

build:
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools-scm
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas <=2.0.3
    - ipython
    - scipy <=1.10.1
    - patsy
    - seaborn
    - plotly
    - matplotlib-base
    - statsmodels
    - scikit-learn <=1.2.2
    - ipfn
    - session-info
    # These dependencies are needed even though not listed in setup files
    - glmnet_py

test:
  source_files:
    - tests
  imports:
    - balance
  commands:
    - pip check
    - pytest -vvv -k "not test_weighted_comparisons_plots and not test_cbps_constraints" --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://import-balance.org/
  dev_url: https://github.com/facebookresearch/balance
  summary: Simple workflow and methods for dealing with biased data.
  license: GPL-2.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
